### ISSUE TITLE
themeColor fail

### ISSUE THREAD

**Issue by tmzdy888** [dmnsgn/typedoc-material-theme#1]
in typedoc.json file:
"themeColor": "#2a66fe"
and:
cli run : npx typeDoc
the page no color theme
so is default color #cb9820

help me. tks!

**Comment by dmnsgn** [comment]
@tmzdy888 TypeDoc was not picking up the theme color option on load.
I have pushed a fix so please run `npm install typedoc-material-theme@1.0.1` and let me know if that works for you.
