### ISSUE TITLE
Bug: bare-minimum scrollbar not working on Chrome 121+

### ISSUE THREAD

**Issue by kabeep** [dmnsgn/typedoc-material-theme#10]
Hi @dmnsgn ,

I noticed that the bare-minimum scrollbar style breaks in Chrome 121 and later. Here’s what seems to be happening:

Material doesn’t fully adopt the latest [scrollbar-* CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color).

Starting with [Chrome 121](https://developer.chrome.com/docs/css-ui/scrollbar-styling), when scrollbar-* properties and pseudo-elements are both applied, the scrollbar-* properties take precedence. This also causes other pseudo-elements that aren’t explicitly overridden to stop working.

Specifically, in this project, it results in a white scrollbar-track and scrollbar-button being displayed, which isn’t an issue on Safari or Firefox.

![image](https://github.com/user-attachments/assets/819803a9-b7ef-4c24-89c9-22a605bd0c4b)

Let me know if more details are needed. Thanks!

**Comment by dmnsgn** [comment]
Released in `typedoc-material-theme@1.2.0`.
