### ISSUE TITLE
Node.js v18 support?

### ISSUE THREAD

**Issue by amiller-gh** [dmnsgn/typedoc-material-theme#2]
For #reasons (it's an Electron app) we can't upgrade our project to use Node v20.

Because this module specifies `"node": ">=20.0.0"` in it's package.json engines, yarn and npm will throw a hard error on install when trying to use the module with any version of node below v20.

I've verified that the theme works just fine on v18 locally. Any way we can remove the engine specifier so module cli's don't yell?

(Yes, I can use the `--ignore-engines` flag, but this is a shared repo and that's a lot to ask of everyone to use every time they want to use a yarn command, and the strict engine check is useful for modules that actually do require v20).

**Comment by amiller-gh** [comment]
Opened a PR with the needed change if this sounds wanted ☝️

**Comment by dmnsgn** [comment]
I tend to follow [Node.js release schedule](https://github.com/nodejs/Release?tab=readme-ov-file#release-schedule) and discard versions not active nor current to avoid any maintenance burden. I'll make an exception here as I don't expect much changes in this package. It should be available in version 1.0.2.

PS: electron v29 should have Node.js 20 🤞
