### ISSUE TITLE
feat: color theme toggle

### ISSUE THREAD

**Issue by TaylorHo** [dmnsgn/typedoc-material-theme#4]
Hi @dmnsgn!

I loved this theme, it's so cooler than the default theme!

As a suggestion, I suggest a **theme toggle**, between dark and light themes. **I want to know what you think about it**. If it's okay, I would like to implement this functionality :)

**Comment by dmnsgn** [comment]
Hi, thanks!

This plugin is mostly updating the styles and actually not touching the html rendering part ([as it brings up more complexity and is prone to more changes](https://github.com/TypeStrong/typedoc/blob/master/internal-docs/custom-themes.md)).

There's already a toggle in the side bar actually and that works well:

<img width="278" alt="image" src="https://github.com/dmnsgn/typedoc-material-theme/assets/1636460/1ad86c6d-d664-4236-9932-c5d0a9f9053d">

It is true I find more usable a toggle in the top bar like the ones from vitepress or docusaurus:

<img width="323" alt="image" src="https://github.com/dmnsgn/typedoc-material-theme/assets/1636460/0ae066ab-9441-49dc-95be-c5c1cbbcbf84">

<img width="514" alt="image" src="https://github.com/dmnsgn/typedoc-material-theme/assets/1636460/0daed619-c696-4670-a75f-438dc8bbdcde">

So maybe that's something you can suggest to the TypeDoc team at https://github.com/TypeStrong/typedoc as an improvement?

**Comment by TaylorHo** [comment]
Ohhh, I didn't see the settings tab, sorry 🤦🏻‍♂️😅
I'll suggest this theme toggle as a potential improvement on the typedoc repository, thanks!

By the way, your typedoc theme is the best one 😁
