### ISSUE TITLE
Bug: page-toolbar styling issue with overlapping elements

### ISSUE THREAD

**Issue by kabeep** [dmnsgn/typedoc-material-theme#8]
Hi there @dmnsgn ,

I ran into some issue with the page toolbar layout in [style.css](https://github.com/dmnsgn/typedoc-material-theme/blob/main/assets/style.css#L100) file.

## What Happen

- When the typedoc config file has multiple navigationLinks properties, the title ends up overlapping the links, making them unclickable.

![image](https://github.com/user-attachments/assets/c36f161a-f48a-4636-be8b-8be3aa278592)

- The title's text-overflow styling messes up the box model, causing the width to not match the actual content, and you can accidentally click into the empty space.

![image](https://github.com/user-attachments/assets/4b017232-4428-4973-8daf-acf42db0293d)

- The search bar input's height and font size are too small, and allowing clicks to pass through to the title and navigation links below it.

![image](https://github.com/user-attachments/assets/b46f0a3b-8a50-47c3-a4e2-c77b8a7e8080)

## See https://dmnsgn.github.io/typedoc-material-theme/ or Reproduction

1. Create a new config file
```json
{
  "name": "@Testing/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis/Ellipsis",
  "navigationLinks": {
    "Docs": "https://typedoc.org/guides/overview",
    "GitHub": "https://github.com/TypeStrong/typedoc"
  }
}
```

2. Run `test` script
3. Check in browser

| Environment | Info |
| - | - |
| typedoc-material-theme | 1.1.0 |
| NodeJS | 18.18.0 |
| Chrome | 130.0.6723.117 (Official Build) (64-bit) |

**Comment by dmnsgn** [comment]
Released in `typedoc-material-theme@1.2.0`.
